export enum ErrorCode {
  // Authentication errors
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN = 'AUTH_EXPIRED_TOKEN',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  // Validation errors
  VALIDATION_INVALID_INPUT = 'VALIDATION_INVALID_INPUT',
  VALIDATION_MISSING_FIELD = 'VALIDATION_MISSING_FIELD',
  VALIDATION_INVALID_FORMAT = 'VALIDATION_INVALID_FORMAT',
  VALIDATION_FAILED = 'VALIDATION_FAILED',

  // Resource errors
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',

  // Credit errors
  CREDITS_INSUFFICIENT = 'CREDITS_INSUFFICIENT',

  // Rate limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Payment errors
  PAYMENT_INSUFFICIENT_CREDITS = 'PAYMENT_INSUFFICIENT_CREDITS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',

  // Job errors
  JOB_NOT_FOUND = 'JOB_NOT_FOUND',
  JOB_ALREADY_PROCESSED = 'JOB_ALREADY_PROCESSED',
  JOB_PROCESSING_FAILED = 'JOB_PROCESSING_FAILED',
  JOB_TIMEOUT = 'JOB_TIMEOUT',

  // Media errors
  MEDIA_UPLOAD_FAILED = 'MEDIA_UPLOAD_FAILED',
  MEDIA_INVALID_FORMAT = 'MEDIA_INVALID_FORMAT',
  MEDIA_TOO_LARGE = 'MEDIA_TOO_LARGE',
  MEDIA_PROCESSING_FAILED = 'MEDIA_PROCESSING_FAILED',

  // AI errors
  AI_GENERATION_FAILED = 'AI_GENERATION_FAILED',
  AI_SERVICE_UNAVAILABLE = 'AI_SERVICE_UNAVAILABLE',
  AI_RATE_LIMITED = 'AI_RATE_LIMITED',

  // Terms errors
  TERMS_NOT_ACCEPTED = 'TERMS_NOT_ACCEPTED',

  // System errors
  SYSTEM_INTERNAL_ERROR = 'SYSTEM_INTERNAL_ERROR',
  SYSTEM_SERVICE_UNAVAILABLE = 'SYSTEM_SERVICE_UNAVAILABLE',
  SYSTEM_RATE_LIMITED = 'SYSTEM_RATE_LIMITED',
}
